### ISSUE TITLE
I can scroll in the settings menu

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar-FE#117] opened 2023-02-06 14:20 UTC
I'm currently spectating a game and I can't scroll

![image](https://user-images.githubusercontent.com/26232486/216995270-838b7444-3bcc-4539-bed4-4f4c39a0839b.png)

**Comment by LaustinSpayce** [comment] 2023-02-06 15:45
Duplicate of #27

**Closed by LaustinSpayce** 2023-02-06 15:45 UTC
Labels: bug
