### ISSUE TITLE
674335 - React-FE bug - Multiple stacks of Shock Charmers don't show

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar-FE#109] opened 2023-02-02 10:40 UTC
Multiple stacks of Shock Charmers don't show how many were used on the side. I think it could be good to test also Seismic Surge as we used the same code for both.

![image](https://user-images.githubusercontent.com/26232486/216302210-6c9e0505-ab28-4f78-b777-0023367c64b1.png)

**Comment by OotTheMonk** [comment] 2023-02-03 01:48
Fixed by deleting this code. It looks like it only ever supported seismic surge and shock charmers. I saw multiple bug reports about shock charmers effect not stacking, but was never able to reproduce. I suspect this was why. If we decide to implement this in the future, we should do it client side. I'm not sure if it's as necessary now though since Awakening is banned in both formats and that was the main source of massive amounts of seismics. I play valda and very rarely get above the 3 threshold you sometimes get from Heave. It's kind of satisfying to see a huge pile of seismic surge effect icons.

**Closed by OotTheMonk** 2023-02-03 01:48 UTC
Labels: enhancement
